I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_one.rpy", line 478, in script
    marta 'Марс?'
Exception: Sayer 'marta' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_one.rpy", line 478, in script
    marta 'Марс?'
  File "D:\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'marta' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
CatMars 1.0
Tue Dec 26 19:50:14 2023
